#!/usr/bin/env tsx
/**
 * scripts/suggest-links.ts
 *
 * Internal-link suggester. Walks every article and proposes contextual
 * links to other site surfaces (services, locations, neighborhoods,
 * topic hubs, sibling articles). Output is a Markdown report the editor
 * reviews — the script never modifies article files.
 *
 * Why this exists: topical authority is built by dense, semantically-
 * relevant internal links. A human writer can't keep the entire site
 * map in their head as the journal grows. This script can.
 *
 * Usage:
 *   npm run editorial:links
 *   npm run editorial:links -- --slug=ai-marketing-operation
 */

import { articles, topics, type Article, type Block } from "../lib/journal";
import { services } from "../lib/services";
import { miami } from "../lib/locations";

type LinkTarget = {
  href: string;
  label: string;
  /** Phrases / keywords whose presence in body should trigger a suggestion. */
  triggers: string[];
};

function buildTargets(): LinkTarget[] {
  const out: LinkTarget[] = [];

  for (const s of services) {
    out.push({
      href: `/services/${s.slug}`,
      label: `${s.title} services`,
      triggers: [
        s.title.toLowerCase(),
        s.seo.primaryKeyword.toLowerCase(),
        ...s.seo.secondaryKeywords.map((k) => k.toLowerCase()),
      ],
    });
  }

  for (const t of topics) {
    out.push({
      href: `/journal/topics/${t.slug}`,
      label: `${t.name} topic hub`,
      triggers: [t.name.toLowerCase(), t.primaryKeyword.toLowerCase()],
    });
  }

  out.push({
    href: `/locations/miami`,
    label: "Miami location page",
    triggers: ["miami", "south florida", "miami-dade"],
  });
  for (const n of miami.neighborhoods) {
    out.push({
      href: `/locations/miami/${n.slug}`,
      label: `${n.name} location page`,
      triggers: [
        n.name.toLowerCase(),
        n.seo.primaryKeyword.toLowerCase(),
      ],
    });
  }

  return out;
}

function blocksToParagraphs(body: Block[]) {
  return body
    .map((b, i) => {
      if (b.type === "p") return { i, text: b.text };
      return null;
    })
    .filter((x): x is { i: number; text: string } => x !== null);
}

function findFirstMatch(text: string, trigger: string): number {
  const re = new RegExp(`\\b${trigger.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}\\b`, "i");
  return text.search(re);
}

function suggestForArticle(a: Article, targets: LinkTarget[]) {
  const existing = new Set((a.internalLinks ?? []).map((l) => l.href));
  const paras = blocksToParagraphs(a.body);

  const suggestions: {
    href: string;
    label: string;
    trigger: string;
    snippet: string;
  }[] = [];

  for (const t of targets) {
    if (existing.has(t.href)) continue;
    // Don't suggest a link to a service/topic/location that IS the
    // article's own subject — it's a self-loop and looks spammy.
    if (t.href === `/journal/topics/${a.topic}`) continue;

    for (const p of paras) {
      for (const trig of t.triggers) {
        const idx = findFirstMatch(p.text, trig);
        if (idx >= 0) {
          const start = Math.max(0, idx - 50);
          const end = Math.min(p.text.length, idx + trig.length + 50);
          const snippet = p.text.slice(start, end);
          suggestions.push({
            href: t.href,
            label: t.label,
            trigger: trig,
            snippet: `…${snippet}…`,
          });
          break;
        }
      }
    }
  }

  // De-duplicate by href; keep the first match for each.
  const seen = new Set<string>();
  return suggestions.filter((s) => {
    if (seen.has(s.href)) return false;
    seen.add(s.href);
    return true;
  });
}

function parseArgs(argv: string[]): { slug?: string } {
  const out: { slug?: string } = {};
  for (const a of argv) {
    const m = a.match(/^--slug=(.+)$/);
    if (m) out.slug = m[1];
  }
  return out;
}

function main() {
  const args = parseArgs(process.argv.slice(2));
  const targets = buildTargets();
  const targetArticles = args.slug
    ? articles.filter((a) => a.slug === args.slug)
    : articles;

  console.log("# Internal link suggestions\n");
  console.log(
    "_Generated by `scripts/suggest-links.ts`. Review each, then add to the article's `internalLinks` array (or surface inside the body where the trigger phrase appears)._\n",
  );

  let totalSuggestions = 0;

  for (const a of targetArticles) {
    const suggestions = suggestForArticle(a, targets);
    if (suggestions.length === 0) continue;
    console.log(`## ${a.title}`);
    console.log(`Slug: \`${a.slug}\` · Topic: \`${a.topic}\`\n`);
    for (const s of suggestions) {
      console.log(
        `- **${s.label}** — \`${s.href}\`  \n  Trigger: \`${s.trigger}\`  \n  Snippet: ${s.snippet}\n`,
      );
      totalSuggestions++;
    }
    console.log("");
  }

  console.log(
    `---\n_${totalSuggestions} suggestion${totalSuggestions === 1 ? "" : "s"} across ${targetArticles.length} article${targetArticles.length === 1 ? "" : "s"}._`,
  );
}

main();
